# Generated by Django 4.0.3 on 2022-04-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCoupon',
            new_name='Coupon',
        ),
    ]
